import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import CartProvider from "./providers/CartProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
        {children}
        </CartProvider>
        
        <Footer/>
      </body>
    </html>
  );
}
